# -*- coding: utf-8 -*-
"""it_support_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q3M-5xZrqmBnnzxGsUpIediI7nwXFg_5
"""

import difflib  # Import difflib for fuzzy matching

# Define a dictionary of FAQs
faqs = {
    "1": {
        "question": "What services does your IT consulting firm offer?",
        "answer": "We offer Database Management, Cloud Computing, Network Security, Web Development, and Technical Support."
    },
    "2": {
        "question": "What is your expertise in cloud computing?",
        "answer": "We have certified experts experienced in AWS, Microsoft Azure, and Google Cloud."
    },
    "3": {
        "question": "How can I contact your support team?",
        "answer": "You can reach us via email at support@itconsulting.com or call 123-456-7890."
    },
    "4": {
        "question": "How can we improve our IT infrastructure?",
        "answer": "We assess your infrastructure and recommend upgrades for better performance and security."
    },
    "5": {
        "question": "Which technologies are best suited for our business needs?",
        "answer": "We analyze your operations and suggest the most effective technology solutions."
    },
    "6": {
        "question": "How do we secure our network from cyber threats?",
        "answer": "We implement security measures like firewalls and regular audits to protect your data."
    },
    "7": {
        "question": "What is cloud computing, and how can it benefit our company?",
        "answer": "Cloud computing allows you to access resources online, improving scalability and reducing costs."
    },
    "8": {
        "question": "What is the best way to back up our data?",
        "answer": "We recommend a robust backup solution that includes regular off-site backups."
    },
    "9": {
        "question": "Can you help us with compliance (e.g., GDPR, HIPAA)?",
        "answer": "Yes, we can guide you on compliance requirements and necessary procedures."
    },
    "10": {
        "question": "How do we optimize our IT costs?",
        "answer": "We analyze your expenses to identify areas for cost reduction without compromising quality."
    }
}

# Function to display FAQs
def display_faqs():
    print("\nHere are our most frequently asked questions:")
    for key, faq in faqs.items():
        print(f"{key}. {faq['question']}")
    print("0. Exit")

# Function to search FAQs by keyword or phrase
def search_faqs(query):
    questions = [faq['question'] for faq in faqs.values()]
    close_matches = difflib.get_close_matches(query, questions, n=5, cutoff=0.3)
    if close_matches:
        print("\nHere are the questions that closely match your search:")
        for match in close_matches:
            for key, faq in faqs.items():
                if faq['question'] == match:
                    print(f"{key}. {faq['question']}")
    else:
        print(f"\nNo FAQs found matching '{query}'. Please try another keyword.")

# Function to interact with the user
def chatbot():
    print("Welcome to IT Consulting Firm Support! How can I assist you today?\n")

    while True:
        display_faqs()
        user_input = input("Enter the number of your question, a keyword to search, or '0' to exit: ").strip()

        if user_input == "0":
            print("Thank you for contacting IT Consulting Firm! Have a great day!")
            break
        elif user_input.isdigit() and user_input in faqs:
            print(f"\nAnswer: {faqs[user_input]['answer']}\n")
        else:
            search_faqs(user_input)

if __name__ == "__main__":
    chatbot()

pip install Flask